### ISSUE TITLE
Missing mono script in textmesh object

### ISSUE THREAD

**Issue by malering** [mob-sakai/UIEffect#168]
my version is v3.1.0, and i open project in unity 2018.3.8f, then i find out in sample scene, text mesh pro missing a script, how do i fix that?

**Comment by mob-sakai** [comment]
Hi @malering 
Oh, I'm sorry.
The demo scene does not support TextMeshPro installed with PackageManager because UIEffect is created in Unity 5.5 (how terrible!).
TextMeshPro's conversion tool does not convert it well.
In the near future, I will remove support for legacy TextMeshPro and update the demo scene. :)

If you're in a hurry, try the following steps:

1. Drag & drop `Packages/TextMeshPro/Scripts/TextMeshProUGUI.cs` to the missing script field in the Inspector.
2. Save demo scene and reload it.
3. Set `Bungers Logo SDF` font to TextMeshProUGUI.
4. Input TextMeshProUGUI's text as you like.
5. See [Usage with TextMeshPro](https://github.com/mob-sakai/UIEffect#usage-with-textmeshpro).

**Comment by malering** [comment]
thx for your help. i am not in hurry now,but  i'll try those steps you provided. those shaders are great, nice job

**Comment by mob-sakai** [comment]
ref #166
