### ISSUE TITLE
ShinyUI TextMeshPro shaders are failing to compile.

### ISSUE THREAD

**Issue by MrDizzle** [mob-sakai/UIEffect#201]
ShinyUI TextMeshPro shaders are failing to compile.

Clicking 'Fix' when adding a UIEffect creates the UIShiny material, but the material shader renders pink.

Windows:
Unity 2018.4.16f
 - UIEffects 3.2.0

![image](https://user-images.githubusercontent.com/6336930/74031256-e5fb3380-49a8-11ea-820d-f93496179bbe.png)

The list obscures it here but these shaders are in the 'Failed to compile' section of the dropdown

![image](https://user-images.githubusercontent.com/6336930/74031317-16db6880-49a9-11ea-82bf-6027060edd24.png)

**Comment by mob-sakai** [comment]
Hi @MrDizzle 

Thank you for your reporting!

**Comment by ns2808** [comment]
+1

I get an error in URP when trying to do this with Unity 2020.1.17f

**Comment by GuillemDomenech** [comment]
Is this solved? Cause I'm still having this issue.

**Comment by SirPytan** [comment]
I also have that issue in URP Unity 2020.3.7f1. @mob-sakai Can you please try to fix it?

**Comment by tengiplex** [comment]
Hey everyone, I was able to fix this issue in 2020.3.26f1 in TMP v3...

Shader doesn't compile because TMP's folder path changed.

Fix (for UIEffect 3.2.0):

1) Go to Assets/Coffee/UIExtensions/UIEffect/ForTMPro/Shaders
2) Open TMP_SDF (UIShiny).Shader and TMP_SDF-Mobile (UIShiny).Shader
3) On line 128, 129 of UIShiny Shader and line 94 of Mobile UIShiny Shader, replace:

`#include "Assets/TextMesh Pro/Resources/Shaders/TMPro_Properties.cginc"
#include "Assets/TextMesh Pro/Resources/Shaders/TMPro.cginc"`

with the correct directory

`#include "Assets/TextMesh Pro/Shaders/TMPro_Properties.cginc"
#include "Assets/TextMesh Pro/Shaders/TMPro.cginc"`

(same thing with the mobile, but just the property one)

This fixed it for me. Hopefully this will help someone... spent quite a long time troubleshooting. Cheers!

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
