### ISSUE TITLE
TextMeshProUGUI Text with UIEffect and UIEffectTweener component disappeard after scaling

### ISSUE THREAD

**Issue by wangping0214** [mob-sakai/UIEffect#286]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
TextMeshProUGUI Text with UIEffect and UIEffectTweener component disappeard after scaling

**To Reproduce**

1. You can reproduce the issue by following the steps as the screencast shows: 

https://github.com/user-attachments/assets/a0076e13-442a-41d5-80ce-d81df6a3503c

2. The UIEffect with Shiny preset and UIEffectTweener component was added to the TextMeshProUGUI gameobject.

**Expected behavior**
TextMeshProUGUI Text with UIEffect and UIEffectTweener component doesn't disappear after scaling

**Screenshots**

**Environment (please complete the following information):**
 - Version [5.0.1]
 - Platform: [Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [2021.3.41f1]
 - Build options: [IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Hi,
The issue is not reproduced on my environment.

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by wangping0214** [comment]
Thank you very much for your quick reply, the test project and video was attached, we hope it helps.

[TestProject.zip](https://github.com/user-attachments/files/18225294/TestProject.zip)

https://github.com/user-attachments/assets/9e1ae160-b7d3-4888-be3c-c0842c4d95d9

**Comment by mob-sakai** [comment]
👍

**Comment by wangping0214** [comment]
Thank you very much for your quick response. We'll try the new release.
